{{- if and .Values.api.enabled .Values.api.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tunnel-orchestrator.componentName" (dict "root" . "component" "api") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnel-orchestrator.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tunnel-orchestrator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
{{- end }}
{{- if and .Values.worker.enabled .Values.worker.podDisruptionBudget.enabled -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tunnel-orchestrator.componentName" (dict "root" . "component" "worker") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnel-orchestrator.componentLabels" (dict "root" . "component" "worker") | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tunnel-orchestrator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
{{- end }}
