receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 10000
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
  resourcedetection:
    detectors: [env, system]
    timeout: 2s

exporters:
  clickhousetraces:
    datasource: tcp://signoz-clickhouse:9000?database=signoz_traces
    docker_multi_node_cluster: false
    low_cardinal_exception_grouping: false
  clickhousemetricswrite:
    endpoint: tcp://signoz-clickhouse:9000?database=signoz_metrics
    resource_to_telemetry_conversion:
      enabled: true
  clickhouselogsexporter:
    dsn: tcp://signoz-clickhouse:9000/?database=signoz_logs
    timeout: 10s
    sending_queue:
      queue_size: 100

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [clickhousemetricswrite]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [clickhouselogsexporter]
